# The Site Configuration
# 站点配置

# Import the theme
# 引入主题
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# 网页的显示语言。
# 如果与 `_data/locales` 文件夹里的文件名相对应，页面的布局语言也会更改。
# 否则，它将默认使用英语 'en'。
# 示例: zh-CN (简体中文), en (英语), zh-TW (繁体中文)
lang: zh-CN

# Change to your timezone › https://zones.arilyn.cc
# 更改为您所在的时区。示例：Asia/Shanghai
timezone: Asia/Shanghai

# jekyll-seo-tag settings
# 搜索引擎优化(SEO) 插件设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: 我的博客 # the main title / 网站主标题。示例：我的博客

tagline: 分享技术与生活 # it will display as the subtitle / 显示为副标题。示例：分享技术与生活

description:
  >- # used by seo meta and the atom feed / 站点描述，用于 SEO 元数据和 Atom/RSS 订阅。
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
# 填写您站点的协议(http/https)和主机名。注意结尾不要带有斜杠 '/'。
url: "https://ljk4.github.io"

github:
  username: ljk4 # change to your GitHub username / 填入您的 GitHub 用户名

twitter:
  username: twitter_username # change to your Twitter username / 填入您的 Twitter 用户名

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  # 更改为您的全名/昵称，它将用作文章默认作者以及页脚显示的版权声明所有者
  name: 刘健康
  email: example@domain.com # change to your email address / 填入您的电子邮件地址
  links:
    # The first element serves as the copyright owner's link
    # 下面的第一个元素用作点击作者版权时跳转的链接
    - https://twitter.com/username # change to your Twitter homepage / 更改为您的推特或主页链接
    - https://github.com/username # change to your GitHub homepage / 您的 GitHub 主页链接
    # Uncomment below to add more social links
    # 取消下方的注释以添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Site Verification Settings
# 站点所有者验证设置 (通常用于搜索引擎站长平台验证)
webmaster_verifications:
  google: # fill in your Google verification code / 填写 Google 验证代码
  bing: # fill in your Bing verification code / 填写 Bing 验证代码
  alexa: # fill in your Alexa verification code / 填写 Alexa 验证代码
  yandex: # fill in your Yandex verification code / 填写 Yandex 验证代码
  baidu: # fill in your Baidu verification code / 填写百度站点验证代码
  facebook: # fill in your Facebook verification code / 填写 Facebook 验证代码

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings
# `jekyll-seo-tag` 设置结束

# Web Analytics Settings
# 网页访问量数据分析设置
analytics:
  google:
    id: # fill in your Google Analytics ID / 填入 Google Analytics 数据 ID (如: G-XXXX)
  goatcounter:
    id: # fill in your GoatCounter ID / 填入 GoatCounter 统计 ID
  umami:
    id: # fill in your Umami ID / 填入 Umami 站点统计 ID
    domain: # fill in your Umami domain / 填入您的 Umami 服务器域名
  matomo:
    id: # fill in your Matomo ID / 填入您的 Matomo 站点 ID
    domain: # fill in your Matomo domain / 填入您的 Matomo 域名
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token / 填入 Cloudflare Web Analytics 访问令牌
  fathom:
    id: # fill in your Fathom Site ID / 填入 Fathom Site ID

# Page views settings
# 页面浏览量显示设置
pageviews:
  provider: # now only supports 'goatcounter' / 浏览量数据提供商，目前仅支持 'goatcounter'

# Prefer color scheme setting.
# 偏好的颜色主题/显示模式。
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
# 注意：保持为空将默认跟随系统的配色偏好，同时侧边栏左下角将出现
# 一个手动在浅色和深色主题之间切换的按钮及提示。
#
# Available options (可用选项):
#
#     light — Use the light color scheme (强制使用浅色模式)
#     dark — Use the dark color scheme (强制使用深色模式)
#
theme_mode: # [light | dark]

# The CDN endpoint for media resources.
# 全站媒体资源的 CDN 外部节点链接 URL。
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
# 注意：此处一旦配置，所有的媒体文件（网站头像、文章配图、音频视频等）只要路径
# 是以 `/` 开头，都会把该 CDN URL 作为前缀自动添加。
#
# e.g. 'https://cdn.com' (示例：https://cdn.example.com )
cdn:

# the avatar on sidebar, support local or CORS resources
# 头像设置（显示于左侧边栏顶端），支持本地相对路径或跨域 URL。
# 示例: /assets/img/avatar.png 或 https://example.com/avatar.jpg
avatar:

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
# SEO 社交分享时的全站默认缩略图（og:image）。
# 在文章头部通过添加自定义的 `image` 头信息，可以实现文章专属配图覆盖此默认整站图。
social_preview_image: # string, local or CORS resources  / 填入图片地址字符串，支持本地或跨域外链

# boolean type, the global switch for TOC in posts.
# 文章目录 (TOC - Table of Contents) 的全局开关。布尔值 (true/false) 类型。
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  # 评论系统全局开关。留空即视为禁用评论功能。
  provider: # [disqus | utterances | giscus]
  # The provider options are as follows:
  # 各家评论服务提供商的设置选项如下：
  disqus:
    shortname: # fill with the Disqus shortname. / 填写 Disqus shortname
  # utterances settings › https://utteranc.es/  (通过 Github Issues 搭建评论区)
  utterances:
    repo: # <gh-username>/<repo> / 填写 Github 仓库，举例: ljk4/blog-comments
    issue_term: # < url | pathname | title | ...> / Issues 匹配规则，推荐使用 pathname
  # Giscus options › https://giscus.app (基于 Github Discussions 搭建评论区)
  giscus:
    repo: # <gh-username>/<repo> / 填写 Github 仓库，举例: ljk4/blog-comments
    repo_id: # 您可以通过访问 giscus 官网进行授权并获取该 ID，或者留空
    category: # 分类名称
    category_id: # 分类 ID
    mapping: # optional, default to 'pathname' / 可选项，页面映射规则，默认即可
    strict: # optional, default to '0' / 可选项，严格匹配
    input_position: # optional, default to 'bottom' / 输入框显示位置，top(置顶)或 bottom(置底)
    lang: # optional, default to the value of `site.lang` / 界面语言，若留空则跟随 site.lang，也可填入如 zh-CN 强制用中文
    reactions_enabled: # optional, default to the value of `1` / 是否允许讨论表情回应 (1 启用 / 0 关闭)

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
# 自托管网站静态资源库，高级设置（非必用）
assets:
  self_host:
    enabled: # boolean, keep empty means false / 是否开启，留空为 false 即不开启
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    # 指定 Jekyll 作用环境。如果开启此功能，您可以指定它在何种环境下生效:
    # development(本地开发) 还是 production(部署打包)。留空表示双端均应用。
    env: # [development | production]

pwa:
  enabled: true # The option for PWA feature (installable) / 是否开启 PWA 特性（让网站拥有原生 App 般的离线预载和桌面安装体验）
  cache:
    enabled: true # The option for PWA offline cache / 是否开启 PWA 离线缓存加速
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    # 在此处定义的路径将会被 PWA 组件的离线缓存完全剔除。
    # 通常用于配置了“子目录网站”(即另一个子项目也使用了相同的域名根服务器)，以避免拦截它们的页面。
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA (匹配该前缀的链接不会记录缓存)

paginate: 10 # 首页列表及各类归档、标签列表的分页数量（一页展示 10 篇文章）

# The base URL of your site
# 您站点的相对根目录基点路径。正常使用时直接留空。
# 如果您将代码部署在 `https://domain.com/blog/`，则填 `/blog`
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------
# ------------ 注意：下面部分为底层核心或推荐配置，不建议没有充分理解时手动修改 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;" # Markdown 脚注返回页面原位时显示的 HTML 图标
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options / 代码块语法高亮模块的进阶配置选项
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project / 空字符串意味着作用域包含您工程里的所有文件
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts. / 文章里默认启用评论区
      toc: true # Display TOC column in posts. / 文章里默认显示目录结构(TOC)
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      # 切勿修改下面的静态链接结构。除非您完全确定如何修复项目中随之崩塌的其他引用链接集。
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: # 分类名称 category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: # 分类名称 /categories/:name/
